---
title: "CodeBook for cleaning data assignment "
output: html_document
---

## Dataset includes the following files (found in folder "data")

- 'features_info.txt': Shows information about the variables used on the feature vector.
- 'features.txt': List of all features.
- 'activity_labels.txt': Links the class labels with their activity name.
- 'train/X_train.txt': Training set.
- 'train/y_train.txt': Training labels.
- 'test/X_test.txt': Test set.
- 'test/y_test.txt': Test labels.

##Generated datasets:

"merged_dataset": Dataset is created but not returned. It is used to as an intermediary step to generate the "AssignmentSubmission.txt" dataset. This dataset:
- Merges the training and the test sets to create one data set.
- Extracts only the measurements on the mean and standard deviation for each measurement. 
- Uses descriptive activity names to name the activities in the data set
- Appropriately labels the data set with descriptive variable names. 

"AssignmentSubmission.txt":
- Uses the "merged_dataset"
- Contains an observation for every activity (6) for every participant (30) - 180 total, across 79 variables
- These represent an average for the test and train metrics combined for each variable 